In [2]:
import torch

In [9]:
x=torch.rand([3,3])

In [10]:
x

tensor([[0.9899, 0.7260, 0.9090],
        [0.9126, 0.8262, 0.2620],
        [0.3115, 0.4745, 0.3795]])

In [11]:
x.dtype

torch.float32

In [17]:
torch.argmax(x,dim=1)

tensor([0, 0, 1])

In [18]:
torch.max(x)

tensor(0.9899)

In [22]:
x.shape

torch.Size([3, 3])

In [23]:
test_tens=torch.randn([5,2])

In [24]:
test_tens

tensor([[ 0.1452,  1.6216],
        [ 0.3250,  0.0677],
        [-0.7943,  0.4033],
        [ 0.9022,  0.5621],
        [ 0.3685, -0.4253]])

In [25]:
action=torch.Tensor([0,1,1,0,0]).long()

In [40]:
action.view(-1,1)

tensor([[0],
        [1],
        [1],
        [0],
        [0]])

In [27]:
action.dtype

torch.int64

In [30]:
test_tens[:,action]

tensor([[ 0.1452,  1.6216,  1.6216,  0.1452,  0.1452],
        [ 0.3250,  0.0677,  0.0677,  0.3250,  0.3250],
        [-0.7943,  0.4033,  0.4033, -0.7943, -0.7943],
        [ 0.9022,  0.5621,  0.5621,  0.9022,  0.9022],
        [ 0.3685, -0.4253, -0.4253,  0.3685,  0.3685]])

In [41]:
torch.gather(test_tens,1,action.view(-1,1))

tensor([[0.1452],
        [0.0677],
        [0.4033],
        [0.9022],
        [0.3685]])